services:
  ankiweb:
    build: .
    image: ankiweb
    container_name: ankiweb
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8765:8765"
    volumes:
      - ankiweb_data:/data
    env_file:
      - path: .env
        required: false
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - "ALL"

volumes:
  ankiweb_data:
